services:
  backend:
    build:
      context: ./Tech@HubAPI/
      dockerfile: Tech@HubAPI/Dockerfile
    ports:
      - 5000:80
    volumes:
      - type: volume
        source: file-store
        target: /app/git
    environment:
      ASPNETCORE_URLS: http://+:80

  git-server:
    build: ./Tech@HubGitServer/
    ports:
      - 80:80
    volumes:
      - type: volume
        source: file-store
        target: /app/git

volumes:
  file-store:
