services:
  backend:
    depends_on:
      - mysql
    build:
      context: ./Tech@HubAPI/
      dockerfile: Tech@HubAPI/Dockerfile
    ports:
      - 5000:80
    volumes:
      - type: volume
        source: file-store
        target: /app/git
    environment:
      ASPNETCORE_URLS: http://+:80

  git-server:
    build: ./Tech@HubGitServer/
    ports:
      - 80:80
    volumes:
      - type: volume
        source: file-store
        target: /app/git

  mysql:
    image: mysql:5.7
    volumes:
      - database
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_DATABASE: tech-at-hub
      MYSQL_USER: gituser
      MYSQL_PASSWORD: dbpass
    ports:
      - 3306:3306

volumes:
  file-store:
  database:
