name: Integration

on:
  push:
    branches: [main]
  pull_request:

jobs:
  integration_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Prepare Environment
        run: |
          cd integration
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          export TECH_AT_HUB_PATH=$(pwd)
          cd integration
          pytest
